### ISSUE TITLE
Suggestion: default to dgraph 1.1

### ISSUE THREAD

**Issue by davedbase** [Swoorup/dgraph-rs#16]
I almost just walked away from dgraph-rs because I wasn't using it properly. I installed a fresh copy of Dgraph and attempted writing some Rust queries against it to validate this library and got the error:

```
thread 'main' panicked at 'failed to create data: GrpcError(RpcFailure(RpcStatus { status: Unimplemented, details: Some("unknown method Mutate for service api.Dgraph") }))', src/server.rs:1:1
```

This lead me to believe the library was not maintained for the latest version of Dgraph. However luckily I ended up reading the instructions on the README properly and determined you have to activate the latest with a feature flag.

There's are three easy solutions:
1. Use 1.1 as the default
2. Force the feature definition to pull in which feature to use
3. When the mutation error comes above comes back warn the user that they are likely using incompatible versions.

This makes them more attentive to the version being used. Honestly I think a combination of 1 and 3 are the safest bet moving forward,

Thanks for your work on this library. It's saving me a lot of time/effort.

**Comment by ondrowan** [comment]
There was a discussion about this a couple of months ago. This crate didn't have support for Dgraph 1.1 at all and we faced a dilemma what would be the best way to add it. Since we didn't have any stats regarding usage of Dgraph 1.0 and 1.1 (and I heard about teams using both), we decided to support both while not disrupting usage for users stuck on 1.0. That's the reason why using this crate with Dgraph 1.1 is a bit awkward at the moment. However, in the future, when version 1.0 of the crate comes out, support for Dgraph 1.0 will be completely dropped. I don't have any timeline for now.

Regarding (3), there's no way to tell if mutation error is caused by mismatched version or some other reason. I'll have another look a bit later, but maybe it won't do any harm to improve the error message nonetheless.

**Comment by ondrowan** [comment]
I just noticed the exact gRPC error and its variant is helpful enough to identify if version mismatch is indeed an issue, so I'll try to add a more helpful message.

**Comment by davedbase** [comment]
Amazing, thank you @ondrowan. PS. I sang this crates praise on the Dgraph slack. You've done great work here. I'm very appreciative.

**Comment by ondrowan** [comment]
I have added a warning if using Dgraph 1.1+ server with Dgraph 1.0 client in 2d9946a6bd7d5c988fdea5a4e3602592acdb9885.
